language: node_js
node_js:
  - '0.10'
  - '0.11'
script:
  - npm test
  - ./travis.sh
env:
  global:
    - secure: "P2gJ13WKny0dIRdfMYxUeKN4t8m7TZYOJnW1AXla2Q064emFWOH+LW5AZK4RA6Lfu/gMhiBSJGZFrkowd+DrPLx1NJNR0yN1thable0iZbSfgGzbcJHO51kG3qprfcbcN5ZpsprkSuRXar5ard3LpSIS5TYpHd2SVGXPYxg1P9g="
    - secure: "VGoompEo9CZo8HAY3rWeZJQk0gLEO4yYJjlva/T4MWUDvtI81hVbyLj08l9YzL4JISfY9PSaTGXI1k2ZyrwLmpo75bObAtdh/5tMad3BUWAyGEC2LQW45V4RnbmCiudFiVP+H1c3C+MApXZSCXAoVTti7Gws+TBvUtkcaiH4jKA="
