language: node_js
node_js:
  - '0.12'
  - '4'
  - '5'
  - '6'
before_script:
  - ./fixjsdom.sh
script:
  - npm run lint
  - npm run coverage
  - ./travis.sh
sudo: false
cache:
  directories:
    - node_modules
    - examples/00hello/node_modules
addons:
  sauce_connect: true
env:
  global:
    - secure: "P2gJ13WKny0dIRdfMYxUeKN4t8m7TZYOJnW1AXla2Q064emFWOH+LW5AZK4RA6Lfu/gMhiBSJGZFrkowd+DrPLx1NJNR0yN1thable0iZbSfgGzbcJHO51kG3qprfcbcN5ZpsprkSuRXar5ard3LpSIS5TYpHd2SVGXPYxg1P9g="
    - secure: "VGoompEo9CZo8HAY3rWeZJQk0gLEO4yYJjlva/T4MWUDvtI81hVbyLj08l9YzL4JISfY9PSaTGXI1k2ZyrwLmpo75bObAtdh/5tMad3BUWAyGEC2LQW45V4RnbmCiudFiVP+H1c3C+MApXZSCXAoVTti7Gws+TBvUtkcaiH4jKA="
    - secure: "vccSVAXGf9Xv1IJsxl3mHaBiqkPQYlGdUdUjGJdbl/X8pJqtbPJ538JY7anExyfySa9NmqJR/tgIky01AccjHxZKrLRrfeI1IxdVxZxBxP+wGCo5ekeCPahb937veWwAFd8GYMxOQXdTd3UA+KeI5Uz1YTmpMFnz4n5eu3aCYUA="
    - secure: "SM8VYh9xXp5zqqcBj7xWFOb34INZ+t3G66JiJWNg+DmawgTBgiAqefPvA+nPodlD4AW4QB9p7SX+LeJZ1xSfWJKHT+C13DpA3Xw4/WJ53wtvXsYrGbQbIXGRHC7hp8Zy5yAqjxB7msLLnl3rrswU7AIImnAL3fSwmDicaHILjrs="
    - secure: "wGv7th7ze+XT7e82Q+VCowRcK/rDfnJ3Nu0/qV4RJoWLBLry99ow+60VE8tEL3x2KN7I17ycqln6bCc7fMIYpluVM5KeEtHR5ZMwVvZUceEn33u/wiPGdQdOF8tV3LZER+FODhADKus4DGNyOHTv/tJNUOre3Wdur0a0EVzIUiA="
