language: node_js
node_js:
  - '0.10'
  - '0.11'
  - '0.12'
  - 'iojs'
script:
  - npm run lint
  - npm run coverage
  - ./travis.sh
sudo: false
cache:
  directories:
    - node_modules
    - examples/00hello/node_modules
addons:
  sauce_connect: true
env:
  global:
    - secure: "P2gJ13WKny0dIRdfMYxUeKN4t8m7TZYOJnW1AXla2Q064emFWOH+LW5AZK4RA6Lfu/gMhiBSJGZFrkowd+DrPLx1NJNR0yN1thable0iZbSfgGzbcJHO51kG3qprfcbcN5ZpsprkSuRXar5ard3LpSIS5TYpHd2SVGXPYxg1P9g="
    - secure: "VGoompEo9CZo8HAY3rWeZJQk0gLEO4yYJjlva/T4MWUDvtI81hVbyLj08l9YzL4JISfY9PSaTGXI1k2ZyrwLmpo75bObAtdh/5tMad3BUWAyGEC2LQW45V4RnbmCiudFiVP+H1c3C+MApXZSCXAoVTti7Gws+TBvUtkcaiH4jKA="
    - secure: "SGt3ueF83HgtAq/nthyukCAnvcTgJm23ARhAUCUWTexl3LGvX0aSH/z8yQ2XtqSUpMHT1fC8t11KY3wUKq5+sx/+KzEF4CCPDGCgpYewYwdYejFSpdDGAbKkWm6d/sN+0sSj7r/Fzya8p1HC61xbVoMuGhmoNKlVVZAyqthxZig="
    - secure: "SM8VYh9xXp5zqqcBj7xWFOb34INZ+t3G66JiJWNg+DmawgTBgiAqefPvA+nPodlD4AW4QB9p7SX+LeJZ1xSfWJKHT+C13DpA3Xw4/WJ53wtvXsYrGbQbIXGRHC7hp8Zy5yAqjxB7msLLnl3rrswU7AIImnAL3fSwmDicaHILjrs="
    - secure: "pEi2WWOjX6VRl7hKi4fKABz/tF454eb4RJ4UsRcCd3O78huG7dvw9w+VY4JRL3DvB608VlZ1oVdeLk1JATrckxBWKycaBh3g+9qmZ1BUME0TL13f8A3jQ6IL9aJz0tkbVKcAuQR7oD1wpTS5cijNQ6B+KvME6M1a2ZjuQwMfaQs="
